/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

/**
 *
 * @author Dell
 */
public class IssueGRN extends javax.swing.JPanel {

    /**
     * Creates new form IssueGRN
     */
    public IssueGRN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIssuegrn = new javax.swing.JPanel();
        SubpnlforIssuegrn = new javax.swing.JPanel();
        lblBatchNoforIssuegrn = new javax.swing.JLabel();
        lblOrderIDforIssuegrn = new javax.swing.JLabel();
        lblTotalDiscountforIssuegrn = new javax.swing.JLabel();
        lblTotalAmountforIssueGRN = new javax.swing.JLabel();
        lblQtyforIssueGRN = new javax.swing.JLabel();
        cmbBatchNoforIssuegrn = new javax.swing.JComboBox<>();
        lblGoodReceiveNoteNoforIssuegrn = new javax.swing.JLabel();
        cmbOrderIDforIssuegrn = new javax.swing.JComboBox<>();
        txtGoodReceiveNoteNoforIssuegrn = new javax.swing.JTextField();
        txtQtyforIssuegrn = new javax.swing.JTextField();
        txtTotalDiscountforIssuegrn = new javax.swing.JTextField();
        txtTotalAmountforIssuegrn = new javax.swing.JTextField();
        jsIssuegrn = new javax.swing.JSeparator();
        btnConfirmforIssuegrn = new javax.swing.JButton();
        btnViewGoodReceiveNotesforIssuegrn = new javax.swing.JButton();

        pnlIssuegrn.setBackground(new java.awt.Color(153, 153, 255));
        pnlIssuegrn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));

        SubpnlforIssuegrn.setBackground(new java.awt.Color(153, 153, 255));
        SubpnlforIssuegrn.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Issue GRN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblBatchNoforIssuegrn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBatchNoforIssuegrn.setText("Batch No");

        lblOrderIDforIssuegrn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOrderIDforIssuegrn.setText("Order ID");

        lblTotalDiscountforIssuegrn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotalDiscountforIssuegrn.setText("Total Discount");

        lblTotalAmountforIssueGRN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotalAmountforIssueGRN.setText("Total Amount");

        lblQtyforIssueGRN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQtyforIssueGRN.setText("Qty");

        lblGoodReceiveNoteNoforIssuegrn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGoodReceiveNoteNoforIssuegrn.setText("Good Receive Note No");

        jsIssuegrn.setForeground(new java.awt.Color(102, 153, 255));

        btnConfirmforIssuegrn.setText("Confirm");

        btnViewGoodReceiveNotesforIssuegrn.setBackground(new java.awt.Color(255, 255, 255));
        btnViewGoodReceiveNotesforIssuegrn.setText("View Good Receive Notes");

        javax.swing.GroupLayout SubpnlforIssuegrnLayout = new javax.swing.GroupLayout(SubpnlforIssuegrn);
        SubpnlforIssuegrn.setLayout(SubpnlforIssuegrnLayout);
        SubpnlforIssuegrnLayout.setHorizontalGroup(
            SubpnlforIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubpnlforIssuegrnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubpnlforIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsIssuegrn)
                    .addGroup(SubpnlforIssuegrnLayout.createSequentialGroup()
                        .addGroup(SubpnlforIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBatchNoforIssuegrn)
                            .addComponent(lblOrderIDforIssuegrn)
                            .addComponent(lblGoodReceiveNoteNoforIssuegrn)
                            .addComponent(lblQtyforIssueGRN)
                            .addComponent(lblTotalDiscountforIssuegrn)
                            .addComponent(lblTotalAmountforIssueGRN))
                        .addGap(52, 52, 52)
                        .addGroup(SubpnlforIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbBatchNoforIssuegrn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbOrderIDforIssuegrn, 0, 283, Short.MAX_VALUE)
                            .addComponent(txtGoodReceiveNoteNoforIssuegrn)
                            .addComponent(txtQtyforIssuegrn)
                            .addComponent(txtTotalDiscountforIssuegrn)
                            .addComponent(txtTotalAmountforIssuegrn))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubpnlforIssuegrnLayout.createSequentialGroup()
                        .addGap(0, 524, Short.MAX_VALUE)
                        .addComponent(btnViewGoodReceiveNotesforIssuegrn)
                        .addGap(26, 26, 26)
                        .addComponent(btnConfirmforIssuegrn)))
                .addContainerGap())
        );
        SubpnlforIssuegrnLayout.setVerticalGroup(
            SubpnlforIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubpnlforIssuegrnLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(SubpnlforIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SubpnlforIssuegrnLayout.createSequentialGroup()
                        .addGroup(SubpnlforIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SubpnlforIssuegrnLayout.createSequentialGroup()
                                .addGroup(SubpnlforIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBatchNoforIssuegrn)
                                    .addComponent(cmbBatchNoforIssuegrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addGroup(SubpnlforIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblOrderIDforIssuegrn)
                                    .addComponent(cmbOrderIDforIssuegrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(lblGoodReceiveNoteNoforIssuegrn))
                            .addComponent(txtGoodReceiveNoteNoforIssuegrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(SubpnlforIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQtyforIssueGRN)
                            .addComponent(txtQtyforIssuegrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(lblTotalDiscountforIssuegrn))
                    .addComponent(txtTotalDiscountforIssuegrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(SubpnlforIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalAmountforIssueGRN)
                    .addComponent(txtTotalAmountforIssuegrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jsIssuegrn, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SubpnlforIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmforIssuegrn)
                    .addComponent(btnViewGoodReceiveNotesforIssuegrn))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlIssuegrnLayout = new javax.swing.GroupLayout(pnlIssuegrn);
        pnlIssuegrn.setLayout(pnlIssuegrnLayout);
        pnlIssuegrnLayout.setHorizontalGroup(
            pnlIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIssuegrnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubpnlforIssuegrn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlIssuegrnLayout.setVerticalGroup(
            pnlIssuegrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIssuegrnLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(SubpnlforIssuegrn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIssuegrn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIssuegrn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SubpnlforIssuegrn;
    private javax.swing.JButton btnConfirmforIssuegrn;
    private javax.swing.JButton btnViewGoodReceiveNotesforIssuegrn;
    private javax.swing.JComboBox<String> cmbBatchNoforIssuegrn;
    private javax.swing.JComboBox<String> cmbOrderIDforIssuegrn;
    private javax.swing.JSeparator jsIssuegrn;
    private javax.swing.JLabel lblBatchNoforIssuegrn;
    private javax.swing.JLabel lblGoodReceiveNoteNoforIssuegrn;
    private javax.swing.JLabel lblOrderIDforIssuegrn;
    private javax.swing.JLabel lblQtyforIssueGRN;
    private javax.swing.JLabel lblTotalAmountforIssueGRN;
    private javax.swing.JLabel lblTotalDiscountforIssuegrn;
    private javax.swing.JPanel pnlIssuegrn;
    private javax.swing.JTextField txtGoodReceiveNoteNoforIssuegrn;
    private javax.swing.JTextField txtQtyforIssuegrn;
    private javax.swing.JTextField txtTotalAmountforIssuegrn;
    private javax.swing.JTextField txtTotalDiscountforIssuegrn;
    // End of variables declaration//GEN-END:variables
}
